### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by cahana** [cahana/izu-app#1]
Started up application, hit main menu and this error showed up in the logs

2018-11-15 11:45:19.998 ERROR    --- org.thymeleaf.TemplateEngine                                                     : [THYMELEAF][http-nio-8080-exec-1] Exception processing template "main-menu": Error during execution of processor 'org.thymeleaf.standard.processor.text.StandardTextInliningTextProcessor'
2018-11-15 11:45:20.003 ERROR    --- o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/izu].[dispatcherServlet]  : Servlet.service() for servlet [dispatcherServlet] in context with path [/izu] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.standard.processor.text.StandardTextInliningTextProcessor'] with root cause
java.lang.StackOverflowError: null
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.Class.getClasses(Class.java:1498)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.thymeleaf.util.JavaScriptUtils.printObject(JavaScriptUtils.java:360)
	at org.thymeleaf.util.JavaScriptUtils.print(JavaScriptUtils.java:184)
	at org.thymeleaf.util.JavaScriptUtils.printKeyValue(JavaScriptUtils.java:346)

**Comment by cahana** [comment]
I made a bunch of modifications.  The root cause was that I had removed the statistics_id class member variable from the PERSON type because I was following a tutorial.  Adding that variable back into PERSON resolved the issue.

**Comment by cahana** [comment]
The error popped again with the same stacktrace.  Issue was that OneToOne mapping was using FetchType.LAZY.  Switching it to FetchType.EAGER resolved the issue.
